version: '3.3'
services:
  label_nginx:
    image: labelfree/open_frontend:latest
    ports:
      - "${SERVER_PORT}:80"
    restart: always

  label_api:
    image: labelfree/open:latest
    command: gunicorn --conf /code/config/gunicorn.py  --log-config /code/config/logging.conf --chdir /code/labelfree app:app
    volumes:
      - ./backend_log:/var/log/gunicorn
    environment:
      SQLALCHEMY_DATABASE_URI: mysql+pymysql://root:${MYSQL_ROOT_PASSWORD}@label_mysql:3306/labelfree
      REDIS_HOST: label_redis
      REDIS_PORT: 6379
      REDIS_PASSWORD:
      S3_ENDPOINT_URL: http://label-minio:9000
      S3_SECRET_ACCESS_KEY: ${MINIO_ROOT_PASSWORD}
      FLASK_APP: labelfree.app
      LABEL_ENV: dev
      LABEL_BUILD: pro
      LABELFREE_RELEASE: internal
    restart: always

  label_celery_worker:
    image: labelfree/open:latest
    command: celery -A labelfree.app.celery worker -l info -c 4 -B
    environment:
      SQLALCHEMY_DATABASE_URI: mysql+pymysql://root:${MYSQL_ROOT_PASSWORD}@label_mysql:3306/labelfree
      REDIS_HOST: label_redis
      REDIS_PASSWORD:
      S3_ENDPOINT_URL: http://label-minio:9000
      S3_SECRET_ACCESS_KEY: ${MINIO_ROOT_PASSWORD}
      FLASK_APP: labelfree.app
      LABEL_ENV: dev
    restart: always

  label_seg:
    image: labelfree/open_seg:latest
    command: gunicorn --conf /code/config/gunicorn.py  --log-config /code/config/logging.conf --chdir /code/segmentation app:app
    volumes:
      - ./seg_log:/var/log/gunicorn
    environment:
      FLASK_APP: labelfree.app
      SEG_DEBUG: "false"
      G_MAX_REQUESTS: 100
      G_MAX_REQUESTS_JITTER: 10
      SERVER_RUNTIME: "runc"
    restart: always

  label_mysql:
    image: mysql:5.7.22
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: labelfree
    command: --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
      --max_allowed_packet=128M
      --max_connections=1000
      --sql-mode="STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION,NO_ZERO_DATE,NO_ZERO_IN_DATE,ERROR_FOR_DIVISION_BY_ZERO"
    volumes:
      - ./mysql_data:/var/lib/mysql
    restart: always

  label_redis:
    image: redis:5.0.4
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    volumes:
      - ./redis-data:/data
    restart: always
    
  label-minio:
    image: quay.io/minio/minio:RELEASE.2022-11-11T03-44-20Z
    environment:
      MINIO_ROOT_PASSWORD:
      MINIO_ROOT_USER: labelfree
    command: server /data --console-address ":9001"
    volumes:
      - ./minio_data:/data
    restart: always
